### ISSUE TITLE
Error 1 treshold

### ISSUE THREAD

**Issue by iLLiac4** [aenniw/ARDUINO#106]
Can you move Err 1 into plaformio. I have set those parameters into 

#ifdef __USENSOR__
    #define WATCHDOG_TIMEOUT        2000
#else
    #define WATCHDOG_TIMEOUT        100
#endif
#define WATCHDOG_DEADLOCK_CHANGE    2000
#define WATCHDOG_OTHER_CHANGE       100
#ifndef WATCHDOG_OTHER_SLEEP
    #define WATCHDOG_OTHER_SLEEP    0
#endif
#ifdef __H_BRIDGE_MOTOR__
    #define WATCHDOG_TOLERANCE      5
#else
    #define WATCHDOG_TOLERANCE      20
#endif

And it still throws Err.1 constantly. I can not uplift the desk without getting 5x err.1
And even when lowering it it throws err.1

Is there an option to disable err.1 check since i have fuses installed?

**Comment by aenniw** [comment]
you can disable the `watchdog` via removing `__WATCHDOG__` from `platformio.ini` see `build_flags`

**Comment by iLLiac4** [comment]
TNX it works.
