### ISSUE TITLE
Calibration doesn't work

### ISSUE THREAD

**Issue by yusufiga** [aenniw/ARDUINO#107]
EDIT 2: 
Seems like I just messed up with cables all works now. Sorry for the inconvenience.

Hello, 

First of all thank you for the project and sharing with  the community. Lately I have assembled the project. Everything works except calibration.

As it's explained on the documentation while "----" blinking, I start lowering the table and press tilde for 3 seconds then "0000" appears and starts blinking on the screen. When I start pressing up motor rotates and moves up but number on the display doesn't change. From this point on I cannot continue because if I save by using tilde it saves start and end position as 0 and stops moving. If I just don't calibrate and let it blink I can use up and down buttons without any problem

At first I thought KY-040 Rotary Encoder is not working but I doubt that because when I remove the cables and try to move I get Err1. I assume if rotary encoder would be faulty it wouldn't move up and down while it's uncalibrated?

I'm using bridge version. Any idea what could be wrong?

EDIT: 
I just realised on wire diagram, for rotary encoder it's written White: CLK, Gray: DIO. But when I connect White to CLK and Gray to DT(I'm not familiar with abbreviations but there is no DIO so I connected to DT) It gives Err2'

Thanks

**Comment by itaysarig** [comment]
Do you mind explaining exactly what was your wiring issue? I think i have the exact same issue but can't seem to find my wiring mistake.
@yusufiga

**Comment by yusufiga** [comment]
Hi @itaysarig, I was trying to connect wires as it's shown on the image without paying attention to the labels on rotary encoder. 

D2 on Arduino should be connected to CLK on rotary encoder. 
D3 on Arduino should be connected to DT on rotary encoder.

**Comment by itaysarig** [comment]
Thanks for the help tried it out and it fixed it.
