### ISSUE TITLE
BOM list out of date

### ISSUE THREAD

**Issue by harking** [aenniw/ARDUINO#108]
Would you mind updating the BOM list? Some of the links are no longer accessible and not knowing the specs of the items leaves some ambiguity on what to order.

Thanks for the work on this! Looking forward to building!

**Comment by harking** [comment]
Thanks for updating it!

**Comment by harking** [comment]
For: https://github.com/aenniw/ARDUINO/blob/master/skarsta/docs/case_bridge-v1.md
Would you mind adding quantity to the screw types? Thanks!

**Comment by aenniw** [comment]
#113
