### ISSUE TITLE
Err 2 

### ISSUE THREAD

**Issue by itaysarig** [aenniw/ARDUINO#119]
i'm getting the error for no apparent reason. 
I think it might be the amount of time it takes the motor to stop.
also for some reason after setting the boundaries i cannot use the up/down buttons any more.

**Comment by yusufiga** [comment]
if you are trying to move the motor without any load(table weight) motor will not stop in expected time and watchdog will think it's moving unexpectedly. You can either extend watchdog time to 10 second for test purposes or connect to the table and test it.

**Comment by itaysarig** [comment]
Thanks
