### ISSUE TITLE
Motor Pully can't seem to hold the grip on shaft

### ISSUE THREAD

**Issue by itaysarig** [aenniw/ARDUINO#120]
Tried printing the  part using PLA 100% infill a couple of times and PLA couldn't hold at all.
Tried to print use PETG and 100% infill and still it seems the screw that's holding the shaft doesn't seem to have enough  pressure on it.
When facing actual desk load it gives.
Was hoping to know maybe what type of screw I should use or did anyone faced the same issue.

**Comment by iLLiac4** [comment]
Yes printed one is not good. I have used metal one. I think it is listed in readme.

**Comment by itaysarig** [comment]
> Yes printed one is not good. I have used metal one. I think it is listed in readme.

mind linking it? i can't find it

**Comment by iLLiac4** [comment]
https://github.com/aenniw/ARDUINO/issues/24

**Comment by itaysarig** [comment]
> #24

Thank but the link to ebay is a dead link, do you maybe have a live link?
