### ISSUE TITLE
How much weight does your table lift?

### ISSUE THREAD

**Issue by yurazazik** [aenniw/ARDUINO#123]
A question for those who have already assembled this structure. How much weight does your table lift?

**Comment by yurazazik** [comment]
Guys give me feedback please.

**Comment by sxaris87** [comment]
According to the characteristics of the motor we have? with power supply 12V 20A can handle 90kg.cm 
![F73690F6-862F-4184-8ADF-0898C8E33A85](https://user-images.githubusercontent.com/57292949/105895281-fffcae80-601d-11eb-8419-59b950b30fd8.jpeg)
but for me to handle 20A you need to change your cables to thicker, 2-2,5mm. 
I don’t recommend to do that. 
I buy an other power supply 12V 10A because the other that I told you was not good.
![5D35F747-8D86-4351-9282-EFFA771A80D2](https://user-images.githubusercontent.com/57292949/105895216-e9565780-601d-11eb-9a1e-2c0ba27e32d5.png)

**Comment by yurazazik** [comment]
I'm waiting for results your report.

**Comment by yurazazik** [comment]
I'm waiting for results your report. When i measured Amperes of my motor it was 3-4A in maximum mode.

**Comment by sxaris87** [comment]
In relay version that you have your motor works at max rpm? With load max rpm it’s 120? Always according to the motors characteristics.

**Comment by yurazazik** [comment]
> In relay version that you have your motor works at max rpm? With load max rpm it’s 120? Always according to the motors characteristics.

I dont know

**Comment by sxaris87** [comment]
Can you take a video from sitting position to standing?

**Comment by yurazazik** [comment]
> Can you take a video from sitting position to standing?

Yes

**Comment by yurazazik** [comment]
https://youtu.be/gANrgU92JSM

**Comment by yurazazik** [comment]
did you watch?

**Comment by sxaris87** [comment]
Yes.

**Comment by yurazazik** [comment]
> Yes.

and what do you think?

**Comment by sxaris87** [comment]
You use Aluminum Alloy Drive to connect with desk?

**Comment by sxaris87** [comment]
I m thinking about and the only think is the deference in versions relay / h-bridge

**Comment by yurazazik** [comment]
I don't understand, what is problem with your power supply? Was It stop to work?

**Comment by sxaris87** [comment]
I don’t know really. I bought this that I saw you before. 10A to work with no pressure the power supply. The metallic power supply’s is better than the plastic that I have before.

**Comment by yurazazik** [comment]
> I don’t know really. I bought this that I saw you before. 10A to work with no pressure the power supply. The metallic power supply’s is better than the plastic that I have before.

Of course metallic power supply is better

**Comment by yurazazik** [comment]
One of these days another similar motor came from China and, what is most surprising, the table began to work much better and more confidently!!! One of these days another similar motor came from China and, what is most surprising, the table began to work much better and more confidently !!! Now the table raises quite calmly two heavy monitors and everything on the table !!!
