### ISSUE TITLE
7 segment display error code

### ISSUE THREAD

**Issue by sxaris87** [aenniw/ARDUINO#124]

**Comment by sxaris87** [comment]
hello again, i m done with the uploading to arduino and when i turn it on at 7 segment display show me "Err 3" 
what is the problem with wiring?
any ideas?

**Comment by yurazazik** [comment]
Is your circuit already assembled or are you still experimenting with only the arduino board?

**Comment by sxaris87** [comment]
no i made all the connection and when i power it up got "Er 3" but i do it like the wiring diagram. 
what its supposed to be wrong? 
what is the requirements to get this code error?

**Comment by yurazazik** [comment]
What version and sensor did you use?

**Comment by sxaris87** [comment]
h-bridge version. ubridge sensor

**Comment by yurazazik** [comment]
Try to disconnect sensor and switch on table.

**Comment by sxaris87** [comment]
mmm how to do this?

**Comment by yurazazik** [comment]
Show the photo of your connections to 7 segment display.

**Comment by yurazazik** [comment]
sorry to your sensor

**Comment by sxaris87** [comment]
i disconnect ubridge and i connect bridge and now blinking this to display ----

**Comment by sxaris87** [comment]
i think i did it with your help

**Comment by sxaris87** [comment]
i connect to my desk tommorow because with no load get error 2

**Comment by sxaris87** [comment]
thank you very much for your help @yurazazik

**Comment by yurazazik** [comment]
could you take a photo of your assembled circuit?

**Comment by sxaris87** [comment]
yes but not now because its a draft and i have to sleep, i have to go to work in 3 hours :P
