### ISSUE TITLE
Cant set 1,2,3 favorite posisions or min/max if possible 

### ISSUE THREAD

**Issue by sxaris87** [aenniw/ARDUINO#126]
See the video please
https://1drv.ms/u/s!AnyS0ya9TatLnUxrhZwgvosx7SCf?e=GAGVYW

**Comment by sxaris87** [comment]
ok i change
#define SENSOR_PIN0 2
#define SENSOR_PIN1 3
to 
#define SENSOR_PIN0 3
#define SENSOR_PIN1 2
and now it works

**Comment by yurazazik** [comment]
> ok i change
> #define SENSOR_PIN0 2
> #define SENSOR_PIN1 3
> to
> #define SENSOR_PIN0 3
> #define SENSOR_PIN1 2
> and now it works

Can you write on my E-mail?

**Comment by sxaris87** [comment]
sure. 
i think my encoder is not working good. not count well and now again not counting

**Comment by yurazazik** [comment]
> sure.
> i think my encoder is not working good. not count well and now again not counting

Yes, your encoder is not working

**Comment by sxaris87** [comment]
i don't want to print again because i don't have my own printer.
i will order an other encoder
pfff i have spend to many hour at this project till now.

**Comment by yurazazik** [comment]
> i don't want to print again because i don't have my own printer.
> i will order an other encoder
> pfff i have spend to many hour at this project till now.

You don't need to print. You can use double-sided tape to secure the sensor.

**Comment by sxaris87** [comment]
and the perfect spot to put it?
dont need an other code for this?

**Comment by yurazazik** [comment]
> and the perfect spot to put it?
> dont need an other code for this?

I will help you with this

**Comment by yurazazik** [comment]
Can you show you your power supply?

**Comment by sxaris87** [comment]
my father had an other 12V at 5A and work fine

**Comment by sxaris87** [comment]
and how this sensor work really? nothing rotating

**Comment by yurazazik** [comment]
> and how this sensor work really? nothing rotating
Yeesss!

**Comment by yurazazik** [comment]
> my father had an other 12V at 5A and works fine

Can you write a model this power suply?

**Comment by yurazazik** [comment]
> > my father had an other 12V at 5A and works fine
> 
> Can you write a model this power supply?

**Comment by yurazazik** [comment]
I think your encoder is not working because you did the wrong assembly.

**Comment by sxaris87** [comment]
https://1drv.ms/u/s!AnyS0ya9TatLnU1dQ7zv1MlhoRRk

**Comment by sxaris87** [comment]
i dont know what happened, the assembly was like diagramm. 
encoder     CLK to d2
and encoder DT to d3
after not working i change from platformio 
#define SENSOR_PIN0 2
#define SENSOR_PIN1 3
to
#define SENSOR_PIN0 3
#define SENSOR_PIN1 2

and it works but some times loses counting

**Comment by yurazazik** [comment]
> https://1drv.ms/u/s!AnyS0ya9TatLnU1dQ7zv1MlhoRRk
thank you

**Comment by sxaris87** [comment]
the encoder have 5 pins. 
CLK / DT/ SW / + / GND 
and i put it CLK -> D2 
                   DT  -> D3
                   SW -> empy
                    +  -> 5V
                 GND -> GND
m i right?

**Comment by yurazazik** [comment]
> the encoder have 5 pins.
> CLK / DT/ SW / + / GND
> and i put it CLK -> D2
> DT -> D3
> SW -> empy
> + -> 5V
> GND -> GND
> m i right?

yes. It may be 2 problem encoder or your version programm

**Comment by sxaris87** [comment]
2 problem encoder what you mean?
platformio version?

**Comment by yurazazik** [comment]
> 2 problem encoder what you mean?
> platformio version?

Defective Encoder. Yes platformio

**Comment by sxaris87** [comment]
> 
> 
> > 2 problem encoder what you mean?
> > platformio version?
> 
> Defective Encoder. Yes platformio

yes maybe defective, my platformIO version is this:
Version: 1.52.1 (system setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by sxaris87** [comment]
i order now  Distance Measuring Transducer Sensor like yours. 
how i replace the for the new sensor?

**Comment by yurazazik** [comment]
> i order now Distance Measuring Transducer Sensor like yours.
> how i replace the for the new sensor?

<img width="1541" alt="Screenshot 2021-01-20 at 8 28 10 PM" src="https://user-images.githubusercontent.com/77120964/105218667-21612480-5b5e-11eb-85dc-1d691c033570.png">

**Comment by sxaris87** [comment]
> 
> 
> > i order now Distance Measuring Transducer Sensor like yours.
> > how i replace the for the new sensor?
> 
> <img alt="Screenshot 2021-01-20 at 8 28 10 PM" width="1541" src="https://user-images.githubusercontent.com/77120964/105218667-21612480-5b5e-11eb-85dc-1d691c033570.png">

ah ok good semilar diagramm. and the code?

**Comment by sxaris87** [comment]
> 
> 
> > sure.
> > i think my encoder is not working good. not count well and now again not counting
> 
> Yes, your encoder is not working. So I am using USensor! https://github.com/aenniw/ARDUINO/blob/master/skarsta/docs/sensor-sonar.md

is already inside the code of UltraSonicDistanceSensor?

**Comment by yurazazik** [comment]
> > > sure.
> > > i think my encoder is not working good. not count well and now again not counting
> > 
> > 
> > Yes, your encoder is not working. So I am using USensor! https://github.com/aenniw/ARDUINO/blob/master/skarsta/docs/sensor-sonar.md
> 
> is already inside the code of UltraSonicDistanceSensor?

yes

**Comment by sxaris87** [comment]
> > > > sure.
> > > > i think my encoder is not working good. not count well and now again not counting
> > > 
> > > 
> > > Yes, your encoder is not working. So I am using USensor! https://github.com/aenniw/ARDUINO/blob/master/skarsta/docs/sensor-sonar.md
> > 
> > 
> > is already inside the code of UltraSonicDistanceSensor?
> 
> yes

So, when the new SonicSensor arrives, have to replace the defective and that’s all?

**Comment by yurazazik** [comment]
> > > > > конечно. 
> > > > > Я думаю, что мой кодировщик не работает. не считать хорошо и теперь снова не считая
> > > > 
> > > > 
> > > > Да, ваш кодировщик не работает. Так что пользуюсь USensor! https://github.com/aenniw/ARDUINO/blob/master/skarsta/docs/sensor-sonar.md
> > > 
> > > 
> > > уже находится внутри кода UltraSonicDistanceSensor?
> > 
> > 
> > да
> 
> Итак, когда прибудет новый датчик SonicSensor, придется заменить неисправный и все?

3

**Comment by yurazazik** [comment]
> > > > > sure.
> > > > > i think my encoder is not working good. not count well and now again not counting
> > > > 
> > > > 
> > > > Yes, your encoder is not working. So I am using USensor! https://github.com/aenniw/ARDUINO/blob/master/skarsta/docs/sensor-sonar.md
> > > 
> > > 
> > > is already inside the code of UltraSonicDistanceSensor?
> > 
> > 
> > yes
> 
> So, when the new SonicSensor arrives, have to replace the defective and that’s all?

Ofcourse

**Comment by yurazazik** [comment]
But may be your encoder work too, may be this program version mistake

**Comment by sxaris87** [comment]
> But may be your encoder work too, may be this program version mistake. Is this encoder work before?

I don’t know if this encoder work before.
Where can I look for a mistake?

**Comment by yurazazik** [comment]
For this you need download platformio.ini one more time from site and replace it in your work folder

**Comment by sxaris87** [comment]
ok i replace it

**Comment by yurazazik** [comment]
> ok i replace it

tell me when you will finish

**Comment by sxaris87** [comment]
ready. i paste the platformio.ini that i just download from the site to my peoject folder

**Comment by yurazazik** [comment]
now open the project in VSC

**Comment by sxaris87** [comment]
ok.

**Comment by yurazazik** [comment]
<img width="962" alt="Screenshot 2021-01-20 at 11 59 53 PM" src="https://user-images.githubusercontent.com/77120964/105246332-bfafb300-5b7b-11eb-9d77-8baecaa97245.png">

**Comment by yurazazik** [comment]
After that click here

<img width="1118" alt="Screenshot 2021-01-21 at 12 02 06 AM" src="https://user-images.githubusercontent.com/77120964/105246483-fe456d80-5b7b-11eb-8755-70b17828964d.png">

**Comment by sxaris87** [comment]
i follow you

**Comment by yurazazik** [comment]
And choose here 
<img width="1590" alt="Screenshot 2021-01-21 at 12 04 18 AM" src="https://user-images.githubusercontent.com/77120964/105246715-51b7bb80-5b7c-11eb-8684-df434572eccb.png">

**Comment by yurazazik** [comment]
After connect your arduino and compile project
<img width="566" alt="Screenshot 2021-01-21 at 12 07 18 AM" src="https://user-images.githubusercontent.com/77120964/105246957-ace9ae00-5b7c-11eb-887c-8881c185303d.png">

**Comment by yurazazik** [comment]
And will do this 
![Uploading Screenshot 2021-01-21 at 12.08.41 AM.png…]()

**Comment by sxaris87** [comment]
https://ibb.co/tZ6FVdj

**Comment by yurazazik** [comment]
> https://ibb.co/tZ6FVdj

What that? I cannot open this.

**Comment by sxaris87** [comment]
> 
> 
> > https://ibb.co/tZ6FVdj
> 
> What that? I cannot open this.

you can open that? https://1drv.ms/u/s!AnyS0ya9TatLnU4tNlZV8F6ZEQx1?e=JvEW6C

**Comment by sxaris87** [comment]
https://1drv.ms/u/s!AnyS0ya9TatLnU_OpM2X08jGpEwV?e=o6ErJ5

**Comment by yurazazik** [comment]
I can now. So you compiled and you transfer program in arduino

**Comment by yurazazik** [comment]
Connect power supply and try to work with table

**Comment by sxaris87** [comment]
need to disconnect usb from pc to connect the power supply or it's ok to have them both connected?

**Comment by sxaris87** [comment]
ok i uploaded and when i press up. Err1 on display

**Comment by yurazazik** [comment]
> ok i uploaded and when i press up. Err1 on display

show me your configuration.h

**Comment by sxaris87** [comment]
https://1drv.ms/u/s!AnyS0ya9TatLnVD15K0WcH2TlcnP?e=2nZsJr

**Comment by yurazazik** [comment]
> https://1drv.ms/u/s!AnyS0ya9TatLnVD15K0WcH2TlcnP?e=2nZsJr

and MotorBridge.h

**Comment by sxaris87** [comment]
https://1drv.ms/u/s!AnyS0ya9TatLnVHs8lMMYOrig9te?e=HCQn1m

**Comment by yurazazik** [comment]
In MotorBridge.h change this like that
#define MIN_SPEED 255
#define MAX_SPEED 255
#define SPEED_STEP_DURATION 0

**Comment by sxaris87** [comment]
moved almost 1cm and Er 1

**Comment by yurazazik** [comment]
> In MotorBridge.h change this like that
> #define MIN_SPEED 255
> #define MAX_SPEED 255
> #define SPEED_STEP_DURATION 0
> 
> After this save file and compile and transfer in arduino

Did you try this?

**Comment by sxaris87** [comment]
yes and moved up 1cm and give again Err 1

**Comment by sxaris87** [comment]
> 
> 
> yes and moved up 1cm and give again Err 1

and now what?

**Comment by yurazazik** [comment]
try this in configuration.h
<img width="383" alt="Screenshot 2021-01-21 at 12 45 51 AM" src="https://user-images.githubusercontent.com/77120964/105250241-14eec300-5b82-11eb-81c0-85190462d50f.png">

**Comment by sxaris87** [comment]
oooo its moving with no err 1

**Comment by yurazazik** [comment]
Is memory btn work?

**Comment by sxaris87** [comment]
no. i set min and when i set max and try to go down, the buttons up down doesnt work

**Comment by yurazazik** [comment]
> no. i set min and when i set max and try to go down, the buttons up down doesnt work

show me video

**Comment by sxaris87** [comment]
ok 1min to upload

**Comment by sxaris87** [comment]
https://1drv.ms/v/s!AnyS0ya9TatLnVPmKa2u2J2Fp6cT?e=6Eg2w6

**Comment by yurazazik** [comment]
> https://1drv.ms/u/s!AnyS0ya9TatLnVD15K0WcH2TlcnP?e=2nZsJr

I see mistake

**Comment by sxaris87** [comment]
> 
> 
> > https://1drv.ms/u/s!AnyS0ya9TatLnVD15K0WcH2TlcnP?e=2nZsJr
> 
> I see mistake

tell me

**Comment by yurazazik** [comment]
While display is flashing with dashes, press button set!!! after this go table to lowest position

**Comment by yurazazik** [comment]
after this one more time btn set and go up

**Comment by yurazazik** [comment]
and last time btn set!!!

**Comment by sxaris87** [comment]
While display is flashing with dashes and press button set then the down btn not working

**Comment by yurazazik** [comment]
stop

**Comment by yurazazik** [comment]
i try now on my table

**Comment by yurazazik** [comment]
sorry my fault

**Comment by yurazazik** [comment]
that is correct
While display is flashing with dashes, set table to lowest position
Press "tilde" button for 3s or until message '-rst' shows to confirm lowest position and afterwards set table to highest position
Press "tilde" button for 3s or until message '-rst' shows once more to confirm max position
Afterwards you can use table with min/max soft. limits and custom positions
To set new position just press one of 1, 2, 3 buttons until display shows "set" message
To "goto" preset position just press 1, 2, 3 buttons
To reset min/max bounds and custom positions, press "tilde" once more as previously it was calibrated

**Comment by yurazazik** [comment]
Why did you do this?

ok i change
#define SENSOR_PIN0 2
#define SENSOR_PIN1 3
to
#define SENSOR_PIN0 3
#define SENSOR_PIN1 2
and now it works

**Comment by sxaris87** [comment]
> 
> 
> Why did you do this?
> 
> ok i change
> #define SENSOR_PIN0 2
> #define SENSOR_PIN1 3
> to
> #define SENSOR_PIN0 3
> #define SENSOR_PIN1 2
> and now it works

because when was moving not counting.
now i have it 
> #define SENSOR_PIN0 2
> #define SENSOR_PIN1 3
and still not count

**Comment by yurazazik** [comment]
if you write this

#define SENSOR_PIN0 3
#define SENSOR_PIN1 2

is it OK?

**Comment by sxaris87** [comment]
no. works for 2 min and now i have the same results even 2,3 or 3,2.

**Comment by sxaris87** [comment]
maybe defective encoder?

**Comment by sxaris87** [comment]
i already order sonar sensor and i believe i have it at the next 3-4 days.

**Comment by sxaris87** [comment]
i hope it works with the new one

**Comment by yurazazik** [comment]
put reverce polarity false

**Comment by sxaris87** [comment]
you fixed the watchdog issue that i had and thank you for that

**Comment by sxaris87** [comment]
> 
> 
> put reverse polarity false

same issue

**Comment by yurazazik** [comment]
did you compile?

**Comment by sxaris87** [comment]
> 
> 
> did you compile?

yes. same like before

**Comment by sxaris87** [comment]
can i make the display less bright? its too bright

**Comment by sxaris87** [comment]
from where i change the brightness?

**Comment by yurazazik** [comment]
<img width="644" alt="Screenshot 2021-01-21 at 1 48 20 AM" src="https://user-images.githubusercontent.com/77120964/105254695-d4e00e00-5b8a-11eb-9573-34bd1088c973.png">

**Comment by yurazazik** [comment]
put BRIGHT_LOW or BRIGHT_MEDIUM

**Comment by yurazazik** [comment]
in Display.h

**Comment by sxaris87** [comment]
ok found it. thank you again. i will inform you when the new sensor arrive

**Comment by yurazazik** [comment]
> ok found it. thank you again. i will inform you when the new sensor arrive

I need your help too now

**Comment by yurazazik** [comment]
Can you put on the table about 12 kg and lift it UP and record video?

**Comment by sxaris87** [comment]
Sure but I m at bed now if I can help from here.

**Comment by sxaris87** [comment]
My desk is from  Swedish wood 150x70 only this is 10kg for sure and my monitor 6kg and 1-2kg monitor stand and staff

**Comment by yurazazik** [comment]
My table top is original SKARSTA and i think it less then 10 kg for sure plus on the table about 12 Kg, but when i go UP in hi level my motor start to work to slow.

**Comment by yurazazik** [comment]
When i saw your video your motor work very good with lifting. And now I have question what is wrong?))

**Comment by sxaris87** [comment]
Sorry I fell asleep.
I don’t think it’s the weight your problem.
The deference between our projects it’s  two.
The power supply and the version. 
you have relays and I have h-bridge.
But your power supply it’s 12v 15a if I remember right? And it’s more than enough.
So the relay version it’s possible to be weaker?
With relays it’s able to change the speed of the motor?

**Comment by yurazazik** [comment]
> Sorry I fell asleep.
> I don’t think it’s the weight your problem.
> The deference between our projects it’s two.
> The power supply and the version.
> you have relays and I have h-bridge.
> But your power supply it’s 12v 15a if I remember right? And it’s more than enough.
> So the relay version it’s possible to be weaker?
> With relays it’s able to change the speed of the motor?

No, relay version it is more powerful than bridge. And I did h-bridge before it was not good((

**Comment by sxaris87** [comment]
did you ever put grease into mechanism of the table?

**Comment by yurazazik** [comment]
> did you ever put grease into mechanism of the table?

No, and you?

**Comment by sxaris87** [comment]
yes i put grease from the 1st day i bought it to all mechanism, at the rotation spots, in every spot to avoid rubbing

**Comment by yurazazik** [comment]
Wow, can you show me where exactly need to do this?

**Comment by yurazazik** [comment]
> yes i put Lubricant Oil Grease from the 1st day i bought it to all mechanism, at the rotation spots, in every spot to avoid rubbing

???

**Comment by sxaris87** [comment]
Sure. I m out of home right now

**Comment by sxaris87** [comment]
![29638E6A-07DC-47F3-8638-BF58216B25B9](https://user-images.githubusercontent.com/57292949/105341600-f6bbae00-5be7-11eb-9885-ce3928facd2f.jpeg)
![BBC54E73-0E66-48E0-8B39-1B6C4995D286](https://user-images.githubusercontent.com/57292949/105341604-f7ecdb00-5be7-11eb-8acb-5b732d2e9958.jpeg)

**Comment by sxaris87** [comment]
i m back.
so i put there Lubricant Oil Grease and i dont remember if you can remove the plastic piece to see the mechanism taand grease too

**Comment by yurazazik** [comment]
so i dismantled my desk

**Comment by yurazazik** [comment]
after that i checked the two ends of the hex mechanism

**Comment by yurazazik** [comment]
one end was more greased than the other, add lube for both parts

**Comment by sxaris87** [comment]
good. with handle part its rotating easily?

**Comment by sxaris87** [comment]
you can remove nicely the plastic part to see inside? i dont remember if its removable. to grease bearing too if porsible

**Comment by sxaris87** [comment]
i cant dismantled my desk to see because i have many things under it

**Comment by sxaris87** [comment]
![06081F22-F190-4D9F-89B8-5B13464F6A60](https://user-images.githubusercontent.com/57292949/105355028-1f4ca380-5bfa-11eb-8e5b-205d2cc35a1e.jpeg)

**Comment by yurazazik** [comment]
After that i did set up horizontal of table

**Comment by yurazazik** [comment]
And now my table work much better but is not ideal.  The sum of all things on the table is equal to the tabletop (6kg) + computer (10kg) + keyboard, mouse, sound card + external hard drives (2kg) + second monitor (6.5kg) = 24.5kg !!!

**Comment by sxaris87** [comment]
> And now my table work much better but is not ideal. The sum of all things on the table is equal to the tabletop (6kg) + computer (10kg) + keyboard, mouse, sound card + external hard drives (2kg) + second monitor (6.5kg) = 24.5kg !!!

Glad to hear that works better than before. 24,5 kg is not heave nether light but it’s ok I believe.

**Comment by yurazazik** [comment]
> > And now my table work much better but is not ideal. The sum of all things on the table is equal to the tabletop (6kg) + computer (10kg) + keyboard, mouse, sound card + external hard drives (2kg) + second monitor (6.5kg) = 24.5kg !!!
> 
> Glad to hear that works better than before. 24,5 kg is not heave nether light but it’s ok I believe.

In high position all the same motor work little bit worse - slows down the speed

**Comment by sxaris87** [comment]
your motor is running at full speed?
i slow down mean because moves fast and noise. 
i use this settings now
#define MIN_SPEED 50
#define MAX_SPEED 200
#define SPEED_STEP_DURATION 25

**Comment by yurazazik** [comment]
шт relay version is not possible change speed

**Comment by sxaris87** [comment]
same issue with sonar sensor. why?
trigger -> white (D2)
Echo -> grey (D3)

**Comment by sxaris87** [comment]
need to change in code something?

**Comment by yurazazik** [comment]
Yes

**Comment by yurazazik** [comment]
What version did d you compil?

**Comment by sxaris87** [comment]
version of what?

**Comment by sxaris87** [comment]
i just replace the old rotary with the new sonar

**Comment by yurazazik** [comment]
Did you choose Ubridge?

**Comment by sxaris87** [comment]
i choose bridge like you told me 3 day ago.
now i need ubridge?

**Comment by yurazazik** [comment]
3 days ago It was   For encoder) now you have new sensor! You need take uBridge version now

**Comment by sxaris87** [comment]
ahh ok, i didn't know that. thats why i ask again your help

**Comment by sxaris87** [comment]
ooh looks good now. i put it on desk now to see.

**Comment by yurazazik** [comment]
> ooh looks good now. i put it on desk now to see and i will inform you

And?

**Comment by sxaris87** [comment]
ok have just finished. works perfect now. its counting 20-40-60-80..... etc. its possible be more accurate ?

**Comment by yurazazik** [comment]
I don’t know, my is working the same)

**Comment by yurazazik** [comment]
I ask creator but it’s no answer

**Comment by sxaris87** [comment]
thank you @yurazazik very much. this project finished with you help.
i will search for this if it can be more accurate.
if creator reply to you about than please tell me too.

**Comment by yurazazik** [comment]
> thank you @yurazazik very much. this project finished with your help.
> i will search for this if it can be more accurate.
> if creator reply to you about than please tell me too.

Ok
