### ISSUE TITLE
Usensor

### ISSUE THREAD

**Issue by yurazazik** [aenniw/ARDUINO#127]
@aenniw  after how many cm should the information on the table height be displayed on the screen in the Urelay version and can this be changed or this parameter should be displayed in configuration.h? I output once every 2cm.

**Comment by sxaris87** [comment]
@aenniw i need this too.

**Comment by sxaris87** [comment]
Anything new? About the accuracy of sonar?

**Comment by sxaris87** [comment]
in my case when it’s moving to a higher position it counts per 2cm but when it’s moving to a lower position it counts per 4cm. Who we can do it more accurate? @aenniw

**Comment by yurazazik** [comment]
No 

> in my case when it’s moving to a higher position it counts per 2cm but when it’s moving to a lower position it counts per 4cm and this is happens because it’s moving faster when going down. Who we can do it more accurate? @aenniw

No, the fact is that your sonar is in the wrong place, you need to place it in the center of the table right behind the horizontal bar

**Comment by yurazazik** [comment]
![0-02-0a-c6741f3f1f854c1db36636864126061d24549815ef6f3d1c7218e589300b4642_1c6da27974b1c4](https://user-images.githubusercontent.com/77120964/106671692-90576800-65b7-11eb-87ae-e26e391d9e13.jpg)

**Comment by yurazazik** [comment]
> in my case when it’s moving to a higher position it counts per 2cm but when it’s moving to a lower position it counts per 4cm and this is happens because it’s moving faster when going down. Who we can do it more accurate? @aenniw

So?

**Comment by sxaris87** [comment]
I m a little busy this days and I can’t make the transfer now

**Comment by sxaris87** [comment]
So, nothing new about the accuracy of sonar from creator.

**Comment by yurazazik** [comment]
I think he put this in to do list

Чт, 4 февр. 2021 г. в 01:55, sxaris87 <notifications@github.com>:

**Comment by yurazazik** [comment]
> So, nothing new about the accuracy of sonar from creator.

Did you transfer sonar?

**Comment by sxaris87** [comment]
No, maybe at the next days

**Comment by sxaris87** [comment]
Where can I put it to work fine? 
At the center if I m seating the sonar at 80% hits to my legs 1st 
![B3C0058C-C404-4F0E-88C9-A4CC66883CDB](https://user-images.githubusercontent.com/57292949/107121687-8a55d580-689c-11eb-9445-b228cc753ef4.jpeg)

**Comment by yurazazik** [comment]
> Where can I put it to work fine?
> At the center if I m seating the sonar at 80% hits to my legs 1st
> ![B3C0058C-C404-4F0E-88C9-A4CC66883CDB](https://user-images.githubusercontent.com/57292949/107121687-8a55d580-689c-11eb-9445-b228cc753ef4.jpeg)

You have to remove all cables and metallic parts and put sensor on this place.

**Comment by sxaris87** [comment]
This is not possible. Need an other way

**Comment by yurazazik** [comment]
> This is not possible. Need an other way

Another way is just to move the sensor and check and so on until you find the correct position and remember that the sensor sends sound not only downward but in a certain radius, therefore, there should be nothing about 10-20 cm in radius on the floor and around the sensor.

**Comment by aenniw** [comment]
@yurazazik currently min change to display is 1cm  that is checked each 125ms, configuration extracted and added description see #131

**Comment by aenniw** [comment]
@sxaris87 the possition of usensor is quite tricky as it depends if you have table near the walls or even on the floor uneven/carpet... thus you need to play with it quite a lot

![](http://arcbotics.com/wp-content/uploads//2014/01/Ultasonic-Fail.jpg)

**Comment by yurazazik** [comment]
> @yurazazik currently min change to display is 1cm that is checked each 125ms, configuration extracted and added description see #131

Thank you so much! And what is it file do this check?

**Comment by aenniw** [comment]
Check is performed in [Motor.cpp](https://github.com/aenniw/ARDUINO/blob/master/skarsta/lib/motor/Motor.cpp#L166) and its config is in [Motor.h](https://github.com/aenniw/ARDUINO/blob/master/skarsta/lib/motor/Motor.h#L32)

**Comment by yurazazik** [comment]
> Check is performed in [Motor.cpp](https://github.com/aenniw/ARDUINO/blob/master/skarsta/lib/motor/Motor.cpp#L166) and its config is in [Motor.h](https://github.com/aenniw/ARDUINO/blob/master/skarsta/lib/motor/Motor.h#L32)

Thank you for your reply. I rebuilt the sensor by 10 mm, then by 5 mm, but it began to work much worse than the original version, I returned everything to 20mm by the end

**Comment by sxaris87** [comment]
> > Check is performed in [Motor.cpp](https://github.com/aenniw/ARDUINO/blob/master/skarsta/lib/motor/Motor.cpp#L166) and its config is in [Motor.h](https://github.com/aenniw/ARDUINO/blob/master/skarsta/lib/motor/Motor.h#L32)
> 
> Thank you for your reply. I rebuilt the sensor by 10 mm, then by 5 mm, but it began to work much worse than the original version, I returned everything to 20mm by the end

What are this numbers? Which line? What do you mean you rebuilt the sensor by 10mm?

**Comment by yurazazik** [comment]
> > > Check is performed in [Motor.cpp](https://github.com/aenniw/ARDUINO/blob/master/skarsta/lib/motor/Motor.cpp#L166) and its config is in [Motor.h](https://github.com/aenniw/ARDUINO/blob/master/skarsta/lib/motor/Motor.h#L32)
> > 
> > 
> > Thank you for your reply. I rebuilt the sensor by 10 mm, then by 5 mm, but it began to work much worse than the original version, I returned everything to 20mm by the end
> 
> What are this numbers? Which line? What do you mean you rebuilt the sensor by 10mm?

If you carefully read the posts above, Aenniw kindly told where in the program to change the sensor settings and how to make it show information on the screen every 10 mm for the standard 20mm space

**Comment by sxaris87** [comment]
SENSOR_DELTA_ON     10mm
SENSOR_DELTA_OFF    75mm?
This things you mean you  change?

**Comment by yurazazik** [comment]
> SENSOR_DELTA_ON 10mm
> SENSOR_DELTA_OFF 75mm?
> This things you mean you change?

yes

**Comment by sxaris87** [comment]
> > SENSOR_DELTA_ON 10mm
> > SENSOR_DELTA_OFF 75mm?
> > This things you mean you change?
> 
> yes

And now what is your settings for sensor delta on/off ? Default it’s 10/75 by Aenniw

**Comment by yurazazik** [comment]
> > > SENSOR_DELTA_ON 10mm
> > > SENSOR_DELTA_OFF 75mm?
> > > This things you mean you change?
> > 
> > 
> > yes
> 
> And now what is your settings for sensor delta on/off ? Default it’s 10/75 by Aenniw

When i use - Default it’s 10/75 nothing change. It work as before every 2cm

**Comment by sxaris87** [comment]
And you find the way to make it count every 1cm?

**Comment by yurazazik** [comment]
> And you find the way to make it count every 1cm?

It works very bad. Numbers are constantly jumping here and there. For example, it was just 103 cm then 102 and then again 103 and again 102
