### ISSUE TITLE
What case(s) are required

### ISSUE THREAD

**Issue by DerRheingold** [aenniw/ARDUINO#132]
First of all: awesome idea and thanks for putting it all on GitHub! I wanted to build something like this too :)

What I don't get from the instructions:
- Do I need both cases "case_bridge-v1" AND "case_relays-v1"?

I got that only one panel and one sensor is required, but the cases is confusing me a bit 🤔

Thanks for your work and thanks in advance for your help! 😉👍

**Comment by Maaarsl** [comment]
You have to decide on the version first: **h-bridge or relays**.

A comparison between h-bridge and relays can be found here: https://github.com/aenniw/ARDUINO/issues/114#issuecomment-724548715

**For the relay version you'll need:**
[ARDUINO/skarsta/models/relays/case-modular-aio.stl](https://github.com/aenniw/ARDUINO/blob/master/skarsta/models/relays/case-modular-aio.stl) (it's case-modular-cover.stl and case-modular-frame.stl in one file)
OR
[ARDUINO/skarsta/models/relays/case-non-modular.stl](https://github.com/aenniw/ARDUINO/blob/master/skarsta/models/relays/case-non-modular.stl) (non-modular case)

**For the h-bridge version you'll need:**
[ARDUINO/skarsta/models/h-bridge/case-modular-aio.stl](https://github.com/aenniw/ARDUINO/blob/master/skarsta/models/h-bridge/case-modular-aio.stl) (it's case-modular-cover.stl and case-modular-frame.stl in one file)
OR
[ARDUINO/skarsta/models/h-bridge/case-non-modular.stl](https://github.com/aenniw/ARDUINO/blob/master/skarsta/models/h-bridge/case-non-modular.stl) (non-modular case)
