### ISSUE TITLE
Preset 1 doesn't store new position

### ISSUE THREAD

**Issue by iLLiac4** [aenniw/ARDUINO#14]
Hi I have tested your new code and there is a bug. You can not set memory on keypad 1. It goes always to 0000.

**Comment by aenniw** [comment]
Hi I have added EEPROM clear on first start and updated few things that could case this issue could you recheck current `master` if the issue still persists? Thanks

**Comment by iLLiac4** [comment]
Hi. I have tested the new version and the presets seems to work.
But there is another problem.
If you store the position to one of the presets and you call it the motor starts to spin. And if you press during the movement the button up or down the arduino resets and the last position is lost and with them the calibration. I hope you know what i mean.

Yust call a preset and during movement press button up or down. On of those presses will reset the arduino.

It would be nice if you do press any button during the movement of the motor, the motor should just stop.

**Comment by aenniw** [comment]
Does the reset occurs if you power arduino via mini-usb? Note that while testing it you need to disconect arduino from internal buck-converter...

**Comment by iLLiac4** [comment]
Fixed in latest release so I am closing it.
