### ISSUE TITLE
Female 8 pin socket as gnd/5v slot

### ISSUE THREAD

**Issue by Counfhou** [aenniw/ARDUINO#144]
Hi,
Silly question probably but how did you do the 8 pin sockets as sltos for the gnd/5v?
I thought you would just crimp and ad cables at the bottom and solder everyting together, but it seems as if there are no wire in your picture. Did you use a different method taking less place to connect them al somehow?

thx

**Comment by aenniw** [comment]
Which picture do you mean? Could you link the docs steps that you mean?

**Comment by Counfhou** [comment]
![image](https://user-images.githubusercontent.com/17174931/128978917-c987074d-89ba-4e2a-afe8-67d676821bb8.png)

Thx!

**Comment by aenniw** [comment]
I see, I've just bridged pins on `8-pin socket` inserted it into mount and for the input connected jumper wire from `buck-converter`

I'll extends the docs with more robust explanation regarding it....
