### ISSUE TITLE
Update wiring diagrams for v2 cases, plus other improvements

### ISSUE THREAD

**Issue by HitLuca** [aenniw/ARDUINO#152]
While trying to build this project I noticed that the controller case v2 still shows the wiring diagram for the v1 version. Updating It would make future users experience much better.

Also, in v1 is said how the 16 pin connector slot is made using two female 8 pin Dupont connectors: how would a user make them? My solution was far from robust, so having an explanation would help. There is still a 16 pin connector slot on the v2 variant, but what to put there is not mentioned. 

There is a number of items that don't have a valid link, I would try to keep them online or change the page they point to from an e-commerce website to a spec page of that element.

If possibile, show the actual places where connectors are used in the wiring diagram, so that the user can understand exactly how to set it up: the pictures get full of components/wires very quickly, especially for the controller case

**Comment by HitLuca** [comment]
bump

**Comment by Oeil2L** [comment]
Hello,

I agree with this topic.
I am trying to make this project, my knowledge of electronics is limited.

So the schematic in V1 mode is not easy to understand the length of the wires between the different parts.
I also did not understand in the relays which side corresponds to NC or NO.

Maybe sharing pictures of other members' realizations would also help to understand the wiring.
