### ISSUE TITLE
M3-6mm seems to short for motor-sleeve in case_motor-v2

### ISSUE THREAD

**Issue by sterin** [aenniw/ARDUINO#153]
The shopping lists suggests 12 M3-6mm bolts for securing the sleeve to the motor. However, the face of the sleeve is over 6mm, so the bolts are way too short.

~~Was the original intention 6 x M3-12mm bolts?~~

**Comment by Oeil2L** [comment]
I used 10mm for the sleeve without problem (chamfer needed for that part), and for the others screws for the motor.
