### ISSUE TITLE
Motor Tech Specs

### ISSUE THREAD

**Issue by wawibu** [aenniw/ARDUINO#155]
Hi,
as the link to Banggood link isn't working anymore, could you please share the tech specs - in special case the torque - of your motor?
Thanks

**Comment by travisby** [comment]
I could also use this! Would appreciate it!

**Comment by aronmolnar** [comment]
Should be that one: https://www.amazon.de/gp/product/B09CG6P9DX/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1
