### ISSUE TITLE
Seems good.

### ISSUE THREAD

**Issue by iLLiac4** [aenniw/ARDUINO#17]
Hi.
Have tested your latest code and it seems fine.
I had some strange behaviour with button preset 1 that I could not set the position because as soon as I have pressed and hold the button, the motor started to function insted to hold still and set the position. This has happened only with button preset 1.
After refleshing it once again and reseting it again I did not have the same issue or. at least I could not find it.

Otherwise the feature to stop the motor works great and also the resets of the arduino are now mostly gone. I had a reset of the arduino only when I was playing with button preset 1. And for a note when I am testing the new code I do not have arduino connected to USB, I am using just power when testing.

But overall the logic of the motor now functions much better and with latest patches much less stress is added to the shaft and motors.

I will continue to test it and will report back if I find something that I can definetly identify.

I am still waiting for a coupler from ebay so I will report back the finding as soon as I get the shaft.

One question. What screws have you used to mount the box under the table?
I was thinking to use something like this https://www.ebay.com/itm/M3-M4-Press-In-Copper-Brass-Inserts-Embedded-Knurl-Threaded-Nut-Part-for-Plastic/222518687942?hash=item33cf25b8c6:m:mk-fDQ1VXhikmUhhvSwtU2w:rk:149:pf:0 16mm and with m3 screws.

Also why have you decided to drop screen dim after some time that it was used in first version? Would it be possible to add this into code so that user could decide to enable or disable this feature in a code or. maybe even enable and disable this feature with simultaniusly button press? For example short simultanious press tilt and down button disables the dim and tilt and up button enables the dim function and displays on scren dim0 (disabled) and dim1 (enabled). 

TNX

**Comment by aenniw** [comment]
Regarding the screws I've used [Wood screws](https://www.ebay.com/itm/Brass-M3-M3-5-M4-M5-Phillips-Flat-Head-Self-Tapping-Screw-Tappers-Wood-Screws/192513125953?hash=item2cd2ad2e41:m:mWRvSluz6qDTLDQP3pW_XXw:rk:10:pf:0&var=492600383279) but you need to select apropriate length based on your table top...

And dimm control was purged due to change of TM1637 driver lib. as the new one supports by default just `OFF/MEDIUM/HIGH` but I guess that I will add it back later on... 
Thanks
