### ISSUE TITLE
firmware 0.9 report

### ISSUE THREAD

**Issue by iLLiac4** [aenniw/ARDUINO#18]
Have tested latest release and it is very nice.
One thing that would make even less stress to the motor is for example:
I move to the position 1050 and save it to preset 2. If I am at lets say at 500 position and I select preset 2 it will move the motor to around 1050 but not excatly 1050. And if I press then again preset 2 it will move the motor again a small amount to around 1050. So if I keep pressing preset 2 the motor will always spin a little bit and stop. So to avoid accidental douple preset select of the same preset the logic could be that if the current position is less then 100 away from selected preset the motor will not react to the preset.

I hope i have understand this clearly otherwise I can try again?

TNX

**Comment by aenniw** [comment]
Hi I've added min threshold for position change with  change of 8 but it can be easily changed to any value by changing `#define MINIMUM_POS_CHANGE 8`

Regarding slow start of the motor with current setup with relays its not doable, but with something like [BTS7960B  H-Bridge](https://www.ebay.com/itm/Double-BTS7960B-DC-43A-Stepper-Motor-Driver-H-Bridge-PWM-For-Arduino-Smart-Car/200950936475) it could be done... Could you open an separate issue regarding PWM motor control and I will look into that when get my hands on that H-Bridge?

Thanks
