### ISSUE TITLE
Add dimm option to display

### ISSUE THREAD

**Issue by iLLiac4** [aenniw/ARDUINO#21]
I am opening also this to track it easier.
-------
Q:
Also why have you decided to drop screen dim after some time that it was used in first version? Would it be possible to add this into code so that user could decide to enable or disable this feature in a code or. maybe even enable and disable this feature with simultaniusly button press? For example short simultanious press tilt and down button disables the dim and tilt and up button enables the dim function and displays on scren dim0 (disabled) and dim1 (enabled).

A:
And dimm control was purged due to change of TM1637 driver lib. as the new one supports by default just OFF/MEDIUM/HIGH but I guess that I will add it back later on...
------

**Comment by aenniw** [comment]
Addresed in #22 released in [skarsta-0.9.1](https://github.com/aenniw/ARDUINO/releases/tag/skarsta-0.9.1)
