### ISSUE TITLE
Coupler update - metal one

### ISSUE THREAD

**Issue by iLLiac4** [aenniw/ARDUINO#24]
I have finally received the coupler for the shaft.
This one works much better and is strong since it is made out of metal.
You have to buy one with **6-7mm** specification
https://www.ebay.com/itm/2-3-4-5-6-7-8mm-Aluminum-Flexible-Shaft-Coupling-Rigid-Coupler-Motor-Connector/291882575832?ssPageName=STRK%3AMEBIDX%3AIT&var=590884618019&_trksid=p2057872.m2749.l2649

A have made quick mod for the GT2 wheel .It has 14mm hole.https://www.thingiverse.com/thing:3227567

To secure the screws I would recommned to use some kind of screw glue like this:
https://www.banggood.com/Suleve-M243-50mL-Threadlocker-Screw-Lock-Glue-Multipe-Surface-Medium-Strength-Anaerobic-Adhesive-p-1214087.html?p=8H180110948532015010&custlinkid=17674

**Comment by aenniw** [comment]
Will update the docs with this info and links to ebay and thingverse...
Thanks

**Comment by aenniw** [comment]
Updated docs #29
