### ISSUE TITLE
Mirror mesh X

### ISSUE THREAD

**Issue by iLLiac4** [aenniw/ARDUINO#25]
Today I have mounted the motors into 'production' and some things I have noticed during operation.

Before printing the case for the motor, check if it is positioned right.
If you need to mirror it select "Mesh/Mirror Mesh/Mirror X" this is for Simplify3D.
I have one on the thingverse so you can download it. https://www.thingiverse.com/thing:3227567

Also maybee to consider a little bit of redesigned motors case with the option to access rotor encoder and coupler/shaft if something brake or loosens so there is no need to unscrew the whole case of the table.
Something like smal doors or. just an opening.

**Comment by iLLiac4** [comment]
Fixed the link.

**Comment by aenniw** [comment]
I've added modularized version of case see #28 so electronic parts except **RotaryEncoder** and **Motor** can be easily replaced without need to unmount the whole frame from table.
