### ISSUE TITLE
H-Bridge startup parameters

### ISSUE THREAD

**Issue by iLLiac4** [aenniw/ARDUINO#43]
Which part of the code for H-Bridge is responsible for the startup control of the motor?

I would like to tweak it so the motor will start to work at full speed quicker than at the moment.
ATM it takes almost 3 seconds to achieve the full throttle. And because it is so slow it falls into err.1.
Totally enought would be already 0,5 sec.

**Comment by aenniw** [comment]
Decreasing the **SPEED_STEP_DURATION** in [MotorBridge.h](https://github.com/aenniw/ARDUINO/blob/6004b4ebaa20f23a01ae9f06a4883a93a4a82920/skarsta/lib/motor-bridge/MotorBridge.h#L9) should do it.

**Comment by iLLiac4** [comment]
Great tnx. i have found SPEED_STEP_DURATION 30 best value ATM. Will do also some further tests on the bigger desk during the weekend.
