### ISSUE TITLE
H-Bridge new settings

### ISSUE THREAD

**Issue by iLLiac4** [aenniw/ARDUINO#46]
Hi. After some extended testing and some burned fuses this are the settings that works good for me.
Also have tested it on heavy and low weight table. Also on original IKEA the slow start is very fast so parameter 10 is good and works also to lift heavy weight table at the top level without throving err.1.

One thing I have noted on h-bridge version compared to the relay version is that it is a little slower in lifting and I do not know why because raising speed more than 255 it does not work.
-----------------
Watchdog.h
-----------------
#ifndef  __H_BRIDGE_MOTOR__
#define WATCHDOG_TIMEOUT 10
#define WATCHDOG_DEADLOCK_CHANGE 1
#define WATCHDOG_OTHER_CHANGE 5
#define WATCHDOG_TOLERANCE 5
#else
#define WATCHDOG_TIMEOUT 100
#define WATCHDOG_DEADLOCK_CHANGE 2
#define WATCHDOG_OTHER_CHANGE 5
#define WATCHDOG_TOLERANCE 3
#endif

-----------------
MotorBridge.h
-----------------
#define MIN_SPEED 100
#define MAX_SPEED 255
#define SPEED_STEP_DURATION 10

Some notes:
I think there is no need fo ''Optionally if your PSU doesn't provide any OV/SC protection Overload/Short Circuit Protection currenlty needs to be housed outside of case... later on will provide modified case...'' anymore because fuse with 3/4A works good.

Also worth mentioning is that tables should be perfectly leveled.

As an alternative power supply is ATX power supply with this board https://www.ebay.com/itm/24pin-ATX-Computer-PC-Power-Supply-Bench-Top-Breakout-Board-Module-Adapter-zg5J/223416171152
ATX power supply has already implemented short circuit protection and on the board there are all outputs fused. There are some small ATX power supplies from small form desktop computers that are much smaller and still provide aroud 200W.

**Comment by aenniw** [comment]
Updated WATCHDOG, H-BRIDGE definitions
