### ISSUE TITLE
H-Bridge question

### ISSUE THREAD

**Issue by iLLiac4** [aenniw/ARDUINO#50]
Do you know why version with H-bridge struggles more than with relay. It looks like the motor has less power when using H-Bridge compared to relay one.

**Comment by aenniw** [comment]
Did you test it with `H-BRIGDE` start speed set to max?

**Comment by iLLiac4** [comment]
I am using those:
#include <Arduino.h>
#include <Motor.h>

#define MIN_SPEED 100
#define MAX_SPEED 255
#define SPEED_STEP_DURATION 10

**Comment by aenniw** [comment]
Try to set `MIN_SPEED` to `255` and re-test so that it start on max from the start...
