### ISSUE TITLE
Reversed directions?

### ISSUE THREAD

**Issue by ggajews** [aenniw/ARDUINO#75]
Hi. First of all thanks for the amazing work! I'm almost done, but I noticed a strange thing: apparently my desk is going up counter clock wise, and down clock wise. Is it something that can be adjusted, or maybe I made a mistake somewhere? I tried to just swap motor directions, but that causes the counter to stop working.

**Comment by ggajews** [comment]
Update: I change the ccw/cw functionality in the code and now it works, but it's kind of strange that my desk has reversed directions

**Comment by aenniw** [comment]
Did you tried reversing encoder CLK/DIO channels?

**Comment by ggajews** [comment]
Not sure why but it works. Thanks
