### ISSUE TITLE
Example setup using Hall Encoder

### ISSUE THREAD

**Issue by obertr0n** [aenniw/ARDUINO#93]
Hello, Martin, I have observed that you also included some models for Hall effect motor encoder, but I'm not sure how the encoder would be mechanically connected to the motor.
Mind sharing some more details?
BTW, the link to "Magnetic Hall Encoder - 11PPR" is no longer working.

**Comment by aenniw** [comment]
Will update the link to some reference picture 
![image](https://user-images.githubusercontent.com/6786051/91769420-a4013b80-ebdf-11ea-9f02-2a3a4157e5e7.png)
as it seems `11ppr` models are discontinued so only option are `12ppr`

Regarding the docs, I plan to add more photo docs regarding the new models, however didn't have the time to do it, will try to add more info regarding this week...
