### ISSUE TITLE
Panel cover v2 mesh

### ISSUE THREAD

**Issue by micharaze** [aenniw/ARDUINO#96]
It looks like the mesh of the panel cover v2 is broken. When I try to slice it with Cura, it fills the gap where the display should be stuck. Also the github preview of the cover shows a hole on the Botton: https://github.com/aenniw/ARDUINO/blob/master/skarsta/models/panel-v2/panel-cover.stl

Here a picture of the sliced cover:
![image](https://user-images.githubusercontent.com/26977019/91962928-79ad9c00-ed0d-11ea-9b13-d9fb46c943fe.png)

**Comment by iLLiac4** [comment]
it is not broken it is semi transparent.

**Comment by micharaze** [comment]
Sorry for the word "broken", I mean it's just not working for me. If you can see in the sliced picture, the gap is completely filled out. I also printed it already and its not transparent. Even the 4 holes are not there. 

What did you used for a slicing software?

**Comment by iLLiac4** [comment]
Then take version one.

**Comment by micharaze** [comment]
There is definitely something wrong  with the stl. I opened it with different previewers and 3d tools and all have the same issue. Even Fusion 360 shows that the stl is not a full object, there are missing areas. Cura also gives the message that areas are missing.

**Comment by aenniw** [comment]
Yep, that model is corrupted I didn't noticed it as [PrusaSlicer](https://github.com/prusa3d/PrusaSlicer/releases) fixes them automatically...

Fixed the STLs could you recheck them? [panel-cover.stl](https://github.com/aenniw/ARDUINO/blob/master/skarsta/models/panel-v2/panel-cover.stl) Thx

**Comment by micharaze** [comment]
Looks fine in Cura now, thanks! I will print it tomorrow and check the results.
